# ─────────────────────────────────────────────────────────────────────────────
# Horizontal Pod Autoscalers
#
# Prerequisites:
#   kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
# ─────────────────────────────────────────────────────────────────────────────

# ── API autoscaler ────────────────────────────────────────────────────────────
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: jq-api-hpa
  namespace: job-queue
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind:       Deployment
    name:       jq-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type:               Utilization
          averageUtilization: 60

---
# ── General worker autoscaler ─────────────────────────────────────────────────
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: jq-worker-general-hpa
  namespace: job-queue
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind:       Deployment
    name:       jq-worker-general
  minReplicas: 2
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type:               Utilization
          averageUtilization: 70

---
# ── Email worker autoscaler ───────────────────────────────────────────────────
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: jq-worker-email-hpa
  namespace: job-queue
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind:       Deployment
    name:       jq-worker-email
  minReplicas: 2
  maxReplicas: 30
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type:               Utilization
          averageUtilization: 65

---
# ── Payment worker autoscaler ─────────────────────────────────────────────────
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: jq-worker-payment-hpa
  namespace: job-queue
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind:       Deployment
    name:       jq-worker-payment
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type:               Utilization
          averageUtilization: 60
